Repository nahuellorenzo/recalc, pull requests merged in 2023-05, with the labels that each got.

#11 Arreglo test para la funcion pow que pasa parametro negativo
  test/core.test.js
Labels: test

#14 Arreglo el mensaje de error para el método GET /mul/:a/:b
  src/controllers.js
Labels: enhancement

#15 Arreglo mensaje de error para el metodo GET /div/:a/:b
  src/controllers.js
Labels: enhancement

#17 Arreglo mensaje de error para el metodo GET /add/:a/:b
  src/controllers.js
Labels: enhancement

#18 Arreglo error al guardar segundo argumento en History
  src/models.js
Labels: bug

#19 Arreglo bug de controller SUB
  src/controllers.js
Labels: bug

#20 Agrego parámetro result para la función createHistoryEntry
  src/controllers.js
Labels: bug

#21 Agrego test para comprobar que se guardan todos los parametros
  test/models.test.js
Labels: test

#22 Agrego atributo error al modelo history
  src/controllers.js
  src/models.js
Labels: enhancement

#23 Agrego test para el atributo error y para arreglar valor del resultado del segundo test
  test/models.test.js
Labels: test

#24 Agrego función para obtener todo el historial
  src/controllers.js
Labels: enhancement

#25 Cambio la implementacion de la funcion para llevarla a otro archivo
  src/controllers.js
  src/models.js
Labels: enhancement

#27 Agrego función para borrar todos los registros de History
  src/controllers.js
  src/models.js
Labels: enhancement

#26 Agrego test para verificar que se recupere bien el historial desde la BD
  test/models.test.js
Labels: test

#28 Agrego función para guardar el historial en la BD
  src/controllers.js
Labels: enhancement

#30 Modifico el endpoint de MUL para que guarde la entrada en la BD
  src/controllers.js
Labels: enhancement

#33 Soluciono error con el test de substract
  test/api.test.js
Labels: test

#31 Agrego createHistory para pow
  src/controllers.js
Labels: enhancement

#34 Agrego test para endpoint de power
  test/api.test.js
Labels: test

#36 Agrego test para endpoint de add
  test/api.test.js
Labels: test

#35 Agrego test para el endpoint de multiplicacion
  test/api.test.js
Labels: test

#37 Agrego feature id controller
  src/controllers.js
  src/models.js
Labels: enhancement

#39 Agrego test para el endpoint del id
  test/api.test.js
Labels: test

#40 Agrego sqrt como opción en las operaciones de la aplicación
  src/cli.js
  src/controllers.js
  src/core.js
  src/seed.js
Labels: enhancement

#38 Agrego test para comprobar una suma
  test/api.test.js
Labels: test

#41 Modifico el endpoint de div para que guarde la entrada en la BD
  src/controllers.js
Labels: enhancement

#42 Agrego test y Modifico el endpoint para la division
  src/controllers.js
  test/api.test.js
Labels: test

#43 Agrego test para el endpoint sqrt
  test/api.test.js
Labels: test

#45 Agrego test para comprobar el endPoint de deletedAll
  test/api.test.js
Labels: test

#46 Agrego test para testear endPoint de All
  test/api.test.js
Labels: test

#47 Agrego test para la funcion binary
  test/api.test.js
  test/core.test.js
Labels: test

#48 Agrego feature de filtros por operaciones
  src/controllers.js
  src/models.js
  test/api.test.js
Labels: enhancement
